# Generated by Django 5.2.17 on 2026-08-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('arxiv_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('authors', models.JSONField()),
                ('abstract', models.TextField()),
                ('subjects', models.JSONField()),
                ('score', models.FloatField()),
                ('reproducible', models.BooleanField()),
                ('scraped_at', models.DateTimeField()),
            ],
        ),
    ]
