# Generated by Django 5.2.17 on 2026-08-22 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scraperun'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='source',
            field=models.CharField(default='arXiv', max_length=64),
        ),
        migrations.AddField(
            model_name='paper',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('ingested', 'Ingested'), ('queued', 'Queued'), ('generating', 'Generating'), ('awaiting_review', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='ingested', max_length=20),
        ),
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_entity_id', models.CharField(blank=True, max_length=128)),
                ('generated_code', models.TextField(blank=True)),
                ('run_output', models.TextField(blank=True)),
                ('run_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('repro_summary', models.TextField(blank=True)),
                ('repo_url', models.URLField(blank=True, max_length=500)),
                ('repro_result', models.JSONField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reproduction', to='scraper.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=16)),
                ('code', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('reproduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='scraper.reproduction')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('reproduction', 'index')},
            },
        ),
    ]
