apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hackathon-backend-data

